language: node_js

node_js:
- "node"

cache:
  directories:
  - node_modules

env:
  global:
  - GEMFURY_USER=truesparrow
  # GEMFURY_API_KEY
  - secure: "IZNh18j2Bx/fVQEZOnaaHhtr2xX6bq6vMZqdkgqb+D0sQAOj8gvp3VtyCmxgo7+AFd7WTX54y0heF98Glo6hz9y+3GGdzF8FHdUNVKE+yVYZohGOEkf8pKRYBlBlR+puDHphDVrrsVGAW2TYR1tiebSP/RLn2B4iM6z+Ynwhm+MnnrLzX7vQ9aKkDo8DFoA+kD11wFgR3Y7gR4vVLmv63bzPqp+E9LnzB1dgVsniRfS9nnMKSvKa+7JYadBcfhu71Nr87C5Uk9lehbgEtbpJgeBUL2npd4GDWOYOLKr4FJ285cg2vZv9d3CqOdq+jWZGqmQJp/GhkxRYIr9wECrIDa5Wrls7VML3M+6NnWMvmip8gD+/kw1KytDkJEfWdWapFYV8IB/pOr6zJVNTWOJX29B3C4/53aDCwm2wOREXTjiFJZZJXAJxI1cpYGg1yUoLNm1/ea11i3qkV7C3J75llj7lT8UvD4ZtMPW8Saq0guxU3jH+UXq62eUKbKkgyJEDdLqT33OCqhqqjE0DIU4l9jxIrg32a9vPn5lm6lhqS+c7Z+nMXIl7BZG56vccs1Ril8AFHvHW2QzsL+4v3ob/wIx4fcORycjsB8BaFPu0Mc3ab8z5TY2sWBVS943JpyNvbFD2L8dAfQyd7PUt7p9pYGCJMN8V8Qp5UyvZKyhfWEo="

install:
- npm install --registry=https://npm-proxy.fury.io/${GEMFURY_API_KEY}/${GEMFURY_USER}/ --progress=false

script:
- true

deploy:
- provider: script
  skip_cleanup: true
  script: ./src/togemfury.sh --user ${GEMFURY_USER} --api_key ${GEMFURY_API_KEY}
  on:
    tags: true
